[tool.poetry]
name = "changelogapi"
version = "0.1.0"
description = ""
authors = ["Marcin WÅ‚odarczyk <gonzur75@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
